// Expanded Learn-phase cards per unit. Injected into each lesson before its
// takeaway so learners spend more time absorbing material before the graded
// test. Mentor voice, plain language, no em dashes. Each entry is an array of
// learn cards (text / reveal / emotion / widget) appended to the unit's cards.

export const EXPANDED_CARDS = {
  // ---------------- FOUNDATION ----------------
  contracts: [
    { type: "text", heading: "What you're actually buying", body: "A futures contract is standardized: the quantity, quality, and expiration date are fixed by the exchange. You don't negotiate terms - you only decide price and direction. That standardization is why futures are liquid: every ES contract is identical, so buyers and sellers can trade with each other instantly without haggling." },
    { type: "text", heading: "Long vs. short", body: "Going long means you agree to buy at a locked price - you profit if price rises. Going short means you agree to sell at a locked price - you profit if price falls. Futures let you short as easily as going long, with no need to borrow shares like you would in stocks. Symmetry is the whole point: the market doesn't care which way you think it's going." },
    { type: "reveal", prompt: "If you short one ES contract and price drops 4 points, how much did you make?", answer: "$200. Short means you profit when price falls. 4 points x $50 per point = $200 per contract. The math is identical to being long, just reversed." },
    { type: "text", heading: "Why leverage cuts both ways", body: "Putting up $500 to control $50,000 is a 100:1 notional ratio. A 1% move in your favor doubles your $500. A 1% move against you wipes it out. Beyond that, you owe your broker - that's the part new traders don't believe until it happens. Leverage isn't a gift; it's a multiplier of whatever you already are - disciplined or reckless." },
  ],
  ticks: [
    { type: "text", heading: "Tick size vs. tick value", body: "Tick size is the minimum price increment the contract can move - for ES that's 0.25 points. Tick value is the dollar amount each tick is worth - $12.50 for ES. They're separate ideas: size is about price granularity, value is about money. Knowing both is how you convert 'the market moved' into 'this is what it means to my account.'" },
    { type: "text", heading: "Points vs. ticks", body: "One ES point equals four ticks (since each tick is 0.25). Each point is worth $50 per contract. So when someone says 'ES moved 10 points,' that's 40 ticks and $500 per contract. Traders slip between points and ticks constantly - pick one and be consistent, or the math will bite you." },
    { type: "reveal", prompt: "You're stopped out 3.5 points on ES. What's the dollar loss per contract?", answer: "$175. 3.5 points x $50 = $175. In ticks that's 14 ticks x $12.50 = $175. Same answer, two routes - know both." },
    { type: "text", heading: "Why ticks matter for sizing", body: "Your stop distance in ticks, times the tick value, times the number of contracts equals your dollar risk. Change any one of those three and your risk changes. This is the formula every position-sizing decision runs through - memorize it: risk = (stop ticks) x (tick value) x (contracts)." },
  ],
  micros: [
    { type: "text", heading: "The 10:1 ratio", body: "Every major future has a Micro at one-tenth the size. MES ticks are $1.25 vs. ES at $12.50. MNQ ticks are $0.50 vs. NQ at $5.00. The contract specs scale cleanly - margin, tick value, and point value all divide by ten. Micros aren't a different market; they're the same market in smaller slices." },
    { type: "text", heading: "Why precise sizing matters", body: "With full-size contracts you jump from 1 to 2 - that's doubling your risk. With Micros you can move in tenths: 1 MES, then 3, then 7. That granularity lets you hit a specific dollar risk instead of rounding up to the nearest $50. Precision is what lets a small account survive the learning curve." },
    { type: "reveal", prompt: "You want to risk $40 on a trade with a 4-point stop. How many MES contracts?", answer: "1 MES. A 4-point stop on MES (tick $1.25, 4 ticks per point) = 16 ticks x $1.25 = $20 per contract. To risk $40, trade 2 MES. On full ES, the same stop is $200 per contract - you couldn't even trade one." },
    { type: "text", heading: "When to graduate off Micros", body: "Micros are for learning and for sizing precision, not for hiding. If you're consistently profitable and your account can absorb full-size risk, scaling up to the big contract cuts your relative commission drag. But there's no rush - plenty of pros trade Micros forever because the sizing control is worth it." },
  ],
  "order-types": [
    { type: "text", heading: "Market orders: speed at a price", body: "A market order says 'fill me now at whatever the market offers.' You're guaranteed execution but not price. In a fast market or a thin contract, that 'whatever' can be ugly - slippage of several ticks is normal during news. Use market orders when being in the trade right now matters more than the exact entry." },
    { type: "text", heading: "Limit orders: price at a risk", body: "A limit order says 'fill me only at my price or better.' You're guaranteed price (or no fill) but not execution. The risk is the market runs away without you - you were right about direction but never got in. Limits suit patient entries on levels where price often revisits." },
    { type: "text", heading: "Stops: the automatic exit", body: "A stop order becomes a market order once a trigger price is hit. A stop-loss sits where your trade idea is proven wrong - if price reaches it, you're out, no deliberation. Stop-limit orders add a limit after the trigger, which avoids bad fills but risks no fill at all in fast markets. For exits, plain stops are safer than stop-limits." },
    { type: "reveal", prompt: "You're long and want to exit only if price falls to your stop, but you won't accept a fill below the stop. Which order?", answer: "A stop-limit. The stop triggers at your level; the limit says don't fill worse than that. Trade-off: in a fast crash you may not get filled at all and keep holding the loser. Most traders use plain stops for exits precisely to avoid that trap." },
    { type: "text", heading: "Reading the DOM", body: "The DOM (depth of market) shows resting bids and asks at each price level and the size waiting there. A fat bid wall suggests support; a fat ask wall suggests resistance. But resting orders can be pulled instantly - the DOM shows intention, not commitment. Use it to read liquidity, not to predict price." },
  ],
  sessions: [
    { type: "text", heading: "RTH vs. ETH", body: "Regular Trading Hours (RTH) for equity index futures is roughly 9:30am to 4:00pm ET - the US cash session. Electronic Trading Hours (ETH) is everything else, including overnight. Volume and liquidity concentrate in RTH; ETH is thinner with wider spreads and choppier action. Most day-trading setups are designed for RTH." },
    { type: "text", heading: "The open and the close", body: "The first and last 30 minutes of RTH carry outsized volume and volatility - the 'opening drive' and the 'close.' Many intraday strategies are built specifically around these windows. The middle of the day often goes quiet (the lunch lull), which is when false breakouts multiply. Knowing the session rhythm prevents trading dead air." },
    { type: "reveal", prompt: "It's 1:30pm ET on a Tuesday. What kind of market behavior should you expect?", answer: "The lunch lull. Volume typically drops between roughly 11:30am and 2:00pm ET, spreads widen slightly, and breakouts fail more often. Many pros stand down during this window unless a setup is exceptionally clean." },
    { type: "text", heading: "Overnight gaps and risk", body: "If you hold a position overnight (ETH), you're exposed to gap risk - price can open far from where it closed on news that happened while you slept. Day traders exit before the close specifically to avoid this. The 24-hour clock is a feature for hedgers, not a free pass for speculators to hold risk they can't watch." },
    { type: "text", heading: "Economic releases inside the session", body: "CPI, jobs data, FOMC, and oil inventory all drop at fixed times inside RTH or just before. Around these releases, spreads blow out and fills get violent. Many traders flatten before a major release rather than gamble on the print. Calendar awareness is risk management, not just news-following." },
  ],

  // ---------------- INSTRUMENT PROFILES ----------------
  "es-profile": [
    { type: "text", heading: "Why ES is the benchmark", body: "ES tracks the S&P 500 - the most-watched US equity benchmark. That status means it carries the most institutional flow, the tightest spreads, and the most orderly trends of the index futures. When you learn a setup on ES, you're learning it on the cleanest canvas; every other instrument is a variation on it." },
    { type: "text", heading: "The macro drivers", body: "ES moves on expectations of Fed policy: rate cuts are bullish, hikes are bearish. Hard data like CPI and payrolls shifts those expectations in real time. Earnings seasons add company-specific fuel. And broad risk sentiment - 'risk-on' vs. 'risk-off' - pulls every index together. Understand the macro and you understand the tide the intraday waves move in." },
    { type: "reveal", prompt: "CPI prints hotter than expected. What's the typical first-order reaction in ES?", answer: "Lower. Hotter inflation suggests the Fed stays tighter for longer, which pressures equity valuations. The second-order reaction can be more complicated - a strong economy can be good for earnings - but the knee-jerk is down. Trade the reaction, not the theory." },
    { type: "text", heading: "How ES trends behave", body: "ES trends tend to be stair-stepped: impulse up, consolidation, impulse up. Pullbacks are relatively shallow and orderly compared to tech-heavy NQ. That makes ES forgiving for trailing-stop strategies - your stop is less likely to get wicked out by a random spike. Orderly is why it's the first instrument." },
  ],
  "nq-profile": [
    { type: "text", heading: "The tech weighting", body: "NQ tracks the Nasdaq-100, which is dominated by a handful of mega-cap tech names. That concentration means NQ is extra sensitive to rates (tech valuations discount future cash flows), big-tech earnings, and AI/semiconductor cycles. The same macro print can move NQ twice as much as ES." },
    { type: "text", heading: "Speed and range", body: "NQ's average true range is wider than ES in points, and its moves are faster. A setup that gives you 30 seconds to react on ES may give you 10 on NQ. Wider stops are required, which means smaller size for the same dollar risk. NQ rewards preparation and punishes hesitation." },
    { type: "reveal", prompt: "Same dollar risk, same setup on ES and NQ. Which do you size smaller?", answer: "NQ. Its stops are wider (more volatile), so each contract risks more dollars. To keep total dollar risk equal, you trade fewer NQ contracts. Risk-equal sizing means contract count follows the stop distance, not your conviction." },
    { type: "text", heading: "When NQ leads ES", body: "Because NQ is more sensitive to risk sentiment, it often leads ES at turning points - NQ rolls over first, ES follows. Watching both can give you a few minutes' warning on an ES reversal. This is called intermarket confirmation, and it's a cheap edge if you're already watching both." },
  ],
  "cl-profile": [
    { type: "text", heading: "The supply and demand engine", body: "Crude oil is the most physically real of the futures - it gets pumped, stored, shipped, and burned. Supply (OPEC+ decisions, US shale, geopolitical outages) and demand (economic growth, refining runs, seasonal driving/heating cycles) set the price. When you trade CL you're trading a balance of real-world barrels, not just a sentiment gauge." },
    { type: "text", heading: "The weekly calendar", body: "Tuesday 4:30pm ET: the API inventory estimate. Wednesday 10:30am ET: the EIA official inventory report. These two prints move CL more than anything. Draws (less inventory) are bullish; builds (more inventory) are bearish. Positioning ahead of the EIA is a coin flip; trading after it requires fast, disciplined execution." },
    { type: "reveal", prompt: "EIA shows a surprise crude draw of 5 million barrels. What's the typical immediate move?", answer: "Sharp rally. A large draw means supply tightened unexpectedly. But the move often overshoots and reverses as traders take profit - CL is notorious for false breakouts right after the headline. Confirm before you chase." },
    { type: "text", heading: "False breakouts are the feature, not the bug", body: "CL whipsaws more than any index future. A breakout triggers, stops run, then price reverses to trap the chasers. This is why 'confirm, don't anticipate' is the central rule for CL. Wait for the second leg - the follow-through - before committing. On CL, patience is the edge." },
  ],
  "gc-profile": [
    { type: "text", heading: "What gold actually is", body: "Gold is a store of value and a hedge against monetary debasement. Its price is driven by real interest rates (higher real yields make gold less attractive, since gold pays no yield), the dollar (gold is priced in dollars, so a stronger dollar lowers gold), and safe-haven flows (crises send people into gold). Central bank buying adds a slow structural bid." },
    { type: "text", heading: "Regime, not direction", body: "Gold can trend persistently for months inside a macro regime - say, a falling-rate cycle - then grind sideways for a year when the regime stalls. The skill gold teaches is regime recognition: knowing when trend strategies apply and when they don't. Trading a trend strategy in a sideways gold market is how you bleed to death." },
    { type: "reveal", prompt: "Real yields are rising and the dollar is strengthening. What's the likely path for gold?", answer: "Down. Both forces push against gold - higher real yields make the zero-yield metal less attractive, and a stronger dollar lowers its price. Gold's best regimes come from falling real yields and a weak dollar. Read the regime before you read the chart." },
    { type: "text", heading: "Patience as a position", body: "Gold's persistent trends reward sitting, not trading. The temptation in a trending gold regime is to over-trade - to take profits early and re-enter late, giving back edge. Once you've identified the regime, the discipline is to let the trend do the work and trail. Gold teaches you that not trading is also a decision." },
  ],

  // ---------------- STRATEGY INTROS ----------------
  "trend-intro": [
    { type: "text", heading: "The psychology of trend following", body: "Trend following is emotionally hard: you buy strength, which feels expensive, and you sell weakness, which feels like giving up. Most people want to buy low and sell high - trend followers do the opposite. The edge comes precisely from doing what's uncomfortable: entering after confirmation, not before, and riding the move until the market proves you wrong." },
    { type: "text", heading: "Regime is the whole game", body: "Trend strategies work in trending markets and bleed in ranges. So the first question isn't 'where do I enter?' - it's 'is this market trending?' Consolidation, repeated false breakouts, and price chopping around a midpoint all say 'no trend here.' If the regime is wrong, the best trend entry is no entry at all." },
    { type: "reveal", prompt: "Price broke out, ran 5 points, and is now back inside the range. What just happened, and what's the lesson?", answer: "A false breakout - and a reminder that confirmation matters. A single close beyond the range isn't always enough; some traders wait for a retest that holds, or a second confirming bar. The lesson: the breakout that reverses is the central failure mode of this strategy." },
    { type: "text", heading: "Trailing vs. targeting", body: "Trend following has no profit target - you trail the stop and let the market take you out. That means you'll always give back some of the move. The trade-off: you never cap a winner early, so when the big trend comes, you capture it. This is the opposite of mean reversion, where profit is capped at the opposite band. Pick the exit that matches the strategy." },
    { type: "text", heading: "Position sizing for open-ended winners", body: "Because winners are open-ended but losses are capped at the stop, trend following can be profitable with a low win rate - even 35% correct can make money if winners are 3x losers. The sizing implication: keep risk per trade constant and small, because most trades will lose, and the few winners must be allowed to run. Cutting winners early destroys the math." },
  ],
  "mr-intro": [
    { type: "text", heading: "VWAP as fair value", body: "VWAP (volume-weighted average price) is the average price weighted by volume traded so far in the session. It's the benchmark institutions use to judge whether they got a good fill. Above VWAP = buyers are paying a premium; below = sellers are accepting a discount. VWAP is the intraday 'fair value' line that mean reversion trades back toward." },
    { type: "text", heading: "Bands around VWAP", body: "Standard-deviation bands around VWAP mark statistical extremes. When price tags the upper band, it's stretched; the lower band marks the opposite. Mean reversion enters at a band extreme on a rejection (a bar that closes back inside) and targets a return to VWAP or the opposite band. The bands are a timing tool, not a signal by themselves." },
    { type: "reveal", prompt: "Price is riding the upper VWAP band and the band keeps rising with price. Is this a fade? Why or why not?", answer: "No - or not yet. A band that's rising with price is a trend, not a stretch. Fading a trending band is the classic mean-reversion trap: 'overbought' keeps going. Wait for the band to stop expanding and price to close back inside before fading." },
    { type: "text", heading: "The range break is the killer", body: "Mean reversion fails when a range becomes a trend. The same 'overbought' you were fading becomes the start of a breakout that runs for days. This is why the stop goes beyond the band - if price commits to a new level, you're out, not hoping. The loss is the cost of being wrong about the regime; take it and move on." },
    { type: "text", heading: "Profit is capped, so win rate matters", body: "Because mean reversion targets VWAP or the opposite band, profit per trade is bounded. That means you need a higher win rate than trend following to be profitable - typically above 50%. The edge is consistency: small wins, small losses, high frequency. Discipline on the stop is non-negotiable because the capped winners can't rescue sloppy losers." },
  ],
  "breakout-intro": [
    { type: "text", heading: "Defining the opening range", body: "The opening range is the high and low of the first defined window of the session - often the first 30 or 60 minutes. It frames the day's initial balance. A break of that range with volume often sets the day's direction. The discipline is to wait for the range to form before deciding anything - anticipating the break is how you get stopped out." },
    { type: "text", heading: "Volume confirms the break", body: "A breakout on low volume is suspect - it often reverses. A breakout on volume, where each new bar expands participation, has follow-through. Watching relative volume (this bar vs. the average) is how you separate real breaks from noise. The break tells you direction; the volume tells you whether to believe it." },
    { type: "reveal", prompt: "Price breaks the opening range high but the bar closes back inside the range by the end of the bar. What's the read?", answer: "A failed break - likely a stop-run. The close back inside tells you buyers couldn't hold the new level. This is exactly the false breakout to avoid. Wait for a bar that closes beyond the range, ideally with volume, before committing." },
    { type: "text", heading: "The stop goes back inside", body: "On a breakout long, the stop sits just inside the broken range - if price reclaims the range, the breakout failed and you're out. Tight stops like this keep risk small, which is the whole appeal of breakout trading: the stop is structurally defined by the level, not by an arbitrary dollar amount. Let the market tell you where you're wrong." },
  ],
  "momentum-intro": [
    { type: "text", heading: "Momentum is acceleration, not direction", body: "Momentum trading enters moves that are already accelerating - the trend exists and is speeding up. The entry is the retest after the initial thrust, not the spike itself. Chasing the spike is FOMO; entering the retest is the strategy. The distinction is everything: one wrecks accounts, the other is the edge." },
    { type: "text", heading: "Relative strength as a filter", body: "Within a session, some instruments run harder than others. The one making new highs while the broader market stalls has relative strength (RS) - that's where momentum lives. Long the strongest, short the weakest: you put your capital behind the move that's already working, not the one you wish was working. RS is a leading filter, not a lagging indicator." },
    { type: "reveal", prompt: "An instrument spikes 2% in one bar on huge volume. Where's the right entry - the spike, or after?", answer: "After - the retest. The spike is ignition; chasing it means buying the climax, where risk/reward is worst. The retest of the breakout level, where price holds and resumes, offers a tighter stop and a real edge. Patience after ignition is the whole strategy." },
    { type: "text", heading: "Exits are aggressive", body: "Momentum moves exhaust fast - the same acceleration that makes them profitable makes them reverse sharply. So exits are aggressive: take partials into strength, trail hard under successive lows, and never let a winner round-trip. The mindset is 'I will sell strength,' not 'I will hold and hope.' Momentum rewards decisive exits over greedy ones." },
  ],

  // ---------------- RISK & PSYCHOLOGY ----------------
  "trader-mindset": [
    { type: "text", heading: "The edge isn't the chart", body: "Beginners think the edge is a setup or an indicator. It isn't - setups are everywhere, and everyone sees the same chart. The real edge is consistency: doing the same thing the same way every time, so that the statistical advantage (which exists) can express itself over a large sample. A great strategy traded inconsistently loses; an average strategy traded religiously can win." },
    { type: "emotion", scenario: "You take three losses in a row, all valid setups that simply didn't work. You feel the urge to 'switch it up' or skip the next signal.", prompt: "What's the disciplined response?", options: [
      { emoji: "🛑", label: "Take the next valid setup at normal size - the edge is in the sample, not the last three trades", note: "Correct. Three losses in a row is statistically normal even with a 60% win rate. Switching or skipping breaks the sample that the edge lives in. Your job is execution, not second-guessing the math.", mindsetDelta: 4 },
      { emoji: "🔍", label: "Stop trading for the day to 'protect' yourself", note: "Sometimes right if you feel tilt coming, but done reactively it often becomes avoidance. The question is whether you're tilted or just unlucky - those need different responses.", mindsetDelta: 0 },
      { emoji: "🧪", label: "Change your setup because 'this one isn't working'", note: "This is how edges get abandoned a week before they would have paid. Three trades is not a sample. You're not optimizing; you're panicking.", mindsetDelta: -3 },
    ]},
  ],
  fomo: [
    { type: "text", heading: "The cost of the trade you didn't take", body: "A move you missed cost you nothing. Let that sink in - the unrealized profit of someone else's trade is not your loss. But the move you chase, entering late without a setup, can cost everything. FOMO reframes a non-event (missing a move) as a loss, then pushes you into a real loss. The cure is to remember that not every move is yours." },
    { type: "emotion", scenario: "ES just ripped 15 points in 5 minutes on a news headline. You didn't have a position. Your finger is hovering over 'buy'.", prompt: "What's the disciplined move?", options: [
      { emoji: "⏳", label: "Wait for the pullback and a real setup - the rip is not a signal", note: "Right. A 15-point rip is a reaction already priced in; chasing it means buying the top of a spike. The pullback that holds is the setup. Patience here is the difference between a trader and a gambler.", mindsetDelta: 5 },
      { emoji: "⚡", label: "Buy now before it goes higher", note: "This is pure FOMO. By the time you feel it, the easy money is gone. You're buying someone else's profit-taking. Almost always the next move is a pullback that stops you out.", mindsetDelta: -5 },
      { emoji: "🔁", label: "Short it to 'fade the rip'", note: "Fading a news-driven spike is a different strategy with its own rules - and it's not 'I missed the long so I'll short.' That's revenge, not analysis.", mindsetDelta: -2 },
    ]},
  ],
  "loss-aversion": [
    { type: "text", heading: "The plan owns the exit", body: "Loss aversion is the brain's habit of feeling losses twice as hard as equivalent gains - so you take profits early (to lock the good feeling) and let losers run (to avoid the bad feeling). The fix is mechanical: the plan decides the exit, not your feelings. Target hit, take profit. Stop hit, take the loss. You are the executor, not the decider." },
    { type: "emotion", scenario: "Your trade is at +2 points (your target is +4). You feel the urge to take profit now 'to be safe.'", prompt: "What do you do?", options: [
      { emoji: "🎯", label: "Hold to the planned target - the edge includes the full move", note: "Correct. Cutting winners early to feel safe destroys the expectancy of the strategy. If your plan says +4, you hold to +4 or the stop. The discomfort of giving back paper profit is the cost of the edge.", mindsetDelta: 5 },
      { emoji: "🔒", label: "Take the +2 - a win is a win", note: "This feels safe but is fatal over time. If you cut every winner at half-target and let losers hit full stop, you need a 75%+ win rate just to break even. The math doesn't care about your feelings.", mindsetDelta: -3 },
      { emoji: "🚑", label: "Move the stop to breakeven and 'let it ride'", note: "Moving to breakeven too early gets you stopped out of winners that would have worked. Trail only once the trade has proven itself structurally, not as an anxiety reflex.", mindsetDelta: -1 },
    ]},
  ],
  "revenge-tilt": [
    { type: "text", heading: "What tilt feels like", body: "Tilt is a physiological state: tight chest, racing thoughts, the sense that you 'need' to get the money back. It's not a trading signal - it's a nervous-system alarm. The correct response to tilt is not a trade; it's a break. Recognizing the sensation is the skill; acting on it (by stopping) is the discipline." },
    { type: "emotion", scenario: "You just took a -3 point loss on a sloppy entry you're mad at yourself for. You immediately see 'another setup' forming.", prompt: "What's the right call?", options: [
      { emoji: "🧘", label: "Step away for at least 10 minutes - that 'setup' is tilt talking", note: "Correct. The urge to immediately re-enter is revenge trading, and the 'setup' you see is your brain generating permission to act. A short break resets the state. The market will still be there.", mindsetDelta: 6 },
      { emoji: "🚀", label: "Take it - you need to get the money back fast", note: "This is the literal definition of revenge tilt. 'Get it back fast' means oversized risk on a degraded decision. This is how -3 point losses become -30 point days.", mindsetDelta: -6 },
      { emoji: "📏", label: "Take it but at half size to 'be careful'", note: "Smaller size on tilt is still tilt. You've identified the emotional state but are negotiating with it instead of stopping. Half-size revenge is still revenge.", mindsetDelta: -3 },
    ]},
  ],
  overconfidence: [
    { type: "text", heading: "A hot streak is variance", body: "Winning five trades in a row feels like skill, but in a strategy with a 55% win rate, five-in-a-row happens about 5% of the time - purely by chance. The danger is that you start to believe you've 'figured it out' and increase size. Then variance reverts, the same size now loses more dollars, and the account takes a real hit. Size by the formula, not by confidence." },
    { type: "emotion", scenario: "You're up 6 for 6 on the day and feeling invincible. The next setup is a bit outside your plan but 'feels right.'", prompt: "How do you handle it?", options: [
      { emoji: "📐", label: "Skip it - outside the plan is outside the plan, hot streak or not", note: "Correct. The 6-for-6 is variance, not a new edge. Taking an off-plan trade because you 'feel it' is exactly how streaks end in blowups. The plan is the plan regardless of the last six trades.", mindsetDelta: 5 },
      { emoji: "💰", label: "Take it at double size - ride the hot hand", note: "This is overconfidence in its purest form. The hot hand is a cognitive illusion; doubling size on an off-plan trade is how 6-for-6 becomes 6-for-7-down-a-lot. Protect the streak by following the plan.", mindsetDelta: -6 },
      { emoji: "✋", label: "Take it at normal size, it's fine", note: "Even at normal size, off-plan is off-plan. You're teaching yourself that rules are flexible when you're winning - which means they'll be flexible when you're losing too.", mindsetDelta: -2 },
    ]},
  ],
  "position-sizing": [
    { type: "text", heading: "Risk first, size second", body: "Decide your dollar risk before you look at the chart - say, 1% of your account, or a fixed $50. Then work backwards: with your stop distance in ticks and the tick value, compute how many contracts keep your dollar risk at that number. Most beginners do the opposite - they pick a number of contracts first, then discover the stop is too far, and either over-risk or skip the trade." },
    { type: "reveal", prompt: "Account is $5,000. You risk 1% ($50) per trade. Stop is 4 ES points ($200 per contract). How many contracts?", answer: "Zero full ES - one contract risks $200, which is 4% not 1%. Switch to MES: a 4-point stop is $20 per MES contract, so 2 MES contracts = $40, just under 1%. If your account can't fit the stop on the full contract, use the Micro or skip the trade." },
    { type: "text", heading: "Why fixed dollar risk beats fixed contracts", body: "If you always trade 1 contract, your risk swings with the stop distance - a 2-point stop risks $100, a 5-point stop risks $250, on the same '1 contract.' Fixed dollar risk normalizes this: you trade fewer contracts when the stop is wide, more when it's tight. Your risk per trade is constant, which is what lets the edge compound instead of your risk." },
  ],
  stops: [
    { type: "text", heading: "The stop is where you're wrong", body: "A stop goes where your trade idea is disproven - the level beyond which the setup no longer makes sense. It's not an arbitrary dollar amount and it's not 'how much you can afford to lose.' You find it on the chart first, then size your contracts so that hitting it costs your planned dollar risk. Logic before money." },
    { type: "text", heading: "Mental vs. actual stops", body: "A mental stop ('I'll get out if it hits X') is a wish. An actual working stop order in the market is a commitment. The moment price approaches a mental stop, you'll find a reason to give it 'just a little more room' - and that's how small losses become disasters. Always have the stop order live in the market the moment you're filled." },
    { type: "reveal", prompt: "Your stop is at a level that risks $60, but you wanted to risk $40. What are your options?", answer: "Two: (1) trade fewer contracts (if the instrument allows fractional sizing via Micros) to bring dollar risk down to $40, or (2) skip the trade. Never widen the stop to hit a dollar target - that's inventing risk to fit your budget, and it inverts the logic of stops entirely." },
  ],
  "risk-reward": [
    { type: "text", heading: "Expectancy, not win rate", body: "Expectancy = (win rate x average win) - (loss rate x average loss). A 40% win rate with 2:1 reward:risk is profitable: (0.4 x 2) - (0.6 x 1) = +0.2 per trade in risk units. A 60% win rate with 1:1 is also profitable but smaller. The point: you can be wrong more than half the time and still make money - if your winners are bigger than your losers. Reward:risk is what makes a low win rate viable." },
    { type: "reveal", prompt: "Your strategy wins 45% of the time, averages +3R per win, and loses -1R per loss. What's the expectancy per trade?", answer: "+0.80R. (0.45 x 3) - (0.55 x 1) = 1.35 - 0.55 = +0.80. Over 100 trades risking $50 each, that's +$4,000. This is why trend following (low win rate, big winners) works - the math, not the win rate, decides profitability." },
    { type: "text", heading: "Aim for 1.5 to 2x", body: "A 1.5:1 reward:risk means you need only 40% winners to break even; 2:1 needs 34%. Below 1:1, you need to be right more than half the time, which is hard for most strategies. Building setups that target 1.5-2x the stop distance gives you room to be wrong and still profit. It's the single most forgiving parameter you can control." },
  ],
  "daily-loss-limit": [
    { type: "text", heading: "The limit is the lifeline", body: "A daily loss limit is a fixed dollar amount at which you stop trading for the day, no exceptions. Its job is to prevent a bad day from becoming a blown account. Without it, a losing streak triggers tilt, tilt triggers bigger size, and bigger size turns a -$200 day into a -$2,000 day. The limit is the circuit breaker that ends the cascade." },
    { type: "text", heading: "Why it must be mechanical", body: "The limit only works if it's a rule, not a feeling. 'I'll stop if I'm down a lot' is not a limit - 'a lot' expands as you tilt. 'I stop at -$300, period' is a limit. Decide it before the session, when you're calm; honor it during the session, when you're not. The calm version of you is the one who should be in charge." },
    { type: "emotion", scenario: "You've hit your -$300 daily limit at 11am. You feel 'one good trade' away from getting it back.", prompt: "What do you do?", options: [
      { emoji: "🛑", label: "Stop for the day. The limit is the limit.", note: "Correct. The 'one good trade' feeling is tilt masquerading as confidence. The limit exists precisely to override this moment. Tomorrow is a new session; today's job is to not make it worse.", mindsetDelta: 6 },
      { emoji: "🎲", label: "Take one more, then stop if it loses", note: "This is the most expensive sentence in trading. 'One more' becomes 'one more' becomes 'one more.' The limit that bends is not a limit.", mindsetDelta: -6 },
      { emoji: "🪞", label: "Reduce the limit for today so I can keep trading", note: "Adjusting the limit downward to permit more trading is the opposite of a limit. You've made the rule optional at the exact moment it matters most.", mindsetDelta: -5 },
    ]},
  ],

  // ---------------- EXTRA FOUNDATION / INSTRUMENT UNITS ----------------
  "margin-mechanics": [
    { type: "text", heading: "Initial vs. maintenance margin", body: "Initial margin is what you need to open a position; maintenance margin is the lower amount you must keep to hold it. If your account drops to maintenance, you get a margin call - in futures, the broker can liquidate you at the market, often before you decide to close. There's no 'waiting until tomorrow' in futures margin the way there can be in stocks." },
    { type: "text", heading: "Keep a buffer", body: "Trading right at maintenance margin leaves no room for a single adverse tick. Pros keep a comfortable buffer - often 2x initial margin or more - so normal volatility doesn't threaten the position. A buffer is the difference between a position you can hold through a pullback and one that gets liquidated at the worst possible price." },
    { type: "reveal", prompt: "Your position is right at maintenance margin and price ticks against you by one tick. What happens?", answer: "You may be liquidated. One tick below maintenance triggers a margin call, and in futures the broker can close you out at market - often at a worse price than your stop. This is why trading at maintenance is dangerous: a single tick can force an exit you didn't choose." },
  ],
  settlement: [
    { type: "text", heading: "Cash vs. physical settlement", body: "Index futures like ES and NQ settle in cash - at expiration, the difference between your entry and the settlement price is credited or debited, no shares change hands. Physical-delivery futures (CL, GC) can require actual delivery of the commodity, which is why day traders roll out well before first notice day. You never want to accidentally take delivery of 1,000 barrels of oil." },
    { type: "text", heading: "The roll", body: "Because contracts expire, positions that want to stay in the market must 'roll' - close the front-month contract and open the next month. The roll happens before expiration to avoid delivery (for physical) or the illiquid final days. Roll dates are known in advance; mark them so you're never holding into expiration by accident." },
    { type: "reveal", prompt: "You're long ES and the contract expires tomorrow. Do you need to roll?", answer: "Only if you want to stay in the market. ES settles in cash, so at expiration your position simply converts to a cash P&L based on the settlement price - no delivery risk. If you want to keep the trade, roll to the next month today before liquidity thins out." },
  ],
  "contango-backwardation": [
    { type: "text", heading: "The shape of the curve", body: "The futures curve plots contract prices across expiration months. Contango means later months are pricier than near months (an upward-sloping curve); backwardation means near months are pricier (downward-sloping). The shape reflects storage costs, interest, and supply/demand expectations. It's called the 'term structure,' and it shapes every carry trade." },
    { type: "text", heading: "What the roll costs or pays", body: "In contango, rolling a long position means selling a cheap near month and buying a pricier far month - a cost. In backwardation, the roll pays you: sell the expensive near, buy the cheaper far. Over many rolls, this 'roll yield' adds up. It's why some commodity strategies prefer to be long only in backwardated markets." },
    { type: "reveal", prompt: "Oil is in backwardation (near month pricey, far month cheap). You're long and rolling monthly. Is the roll helping or hurting you?", answer: "Helping. Each roll sells the expensive near contract and buys the cheaper far one, capturing the difference as roll yield. This is why backwardation is considered bullish - the market is paying you to stay long, in addition to any price move." },
  ],
  "leverage-math": [
    { type: "text", heading: "Notional vs. risk", body: "Notional leverage (contract value divided by margin) can be 50:1 or more, but that number is misleading. What matters is your dollar risk - the distance to your stop, in dollars, per contract. A 50:1 notional position with a tight 2-point stop may risk less than a 5:1 position with a wide 20-point stop. Notional scares; risk is what actually moves your account." },
    { type: "reveal", prompt: "Two traders each risk $100 per trade. One uses 100:1 notional leverage, the other uses 5:1. Who is taking more risk?", answer: "Neither - they're taking the same dollar risk. The notional ratio is a headline number; the stop distance times tick value times contracts is the real risk. The 100:1 trader just has a tighter stop. Focus on dollar risk, not the leverage headline." },
    { type: "text", heading: "Sizing from the stop, always", body: "Pick dollar risk. Find the stop on the chart (where you're wrong). Convert the stop distance to dollars per contract using tick value. Divide your dollar risk by dollars-per-contract to get the number of contracts. This is the only correct order. Starting from 'how many contracts' and working backwards is how accounts blow up." },
  ],
  "mnq-profile": [
    { type: "text", heading: "Micro Nasdaq", body: "MNQ is one-tenth of NQ - tick value $0.50, point value $2.00. It lets you practice NQ's fast, volatile action with one-tenth the dollar exposure. For learning the most volatile equity index, MNQ is the honest instrument: real NQ behavior, small enough stakes that a learning mistake doesn't wound." },
    { type: "reveal", prompt: "An NQ stop is 15 points. On MNQ, how many dollars is that per contract?", answer: "$30. 15 points x $2/point = $30 per MNQ. On full NQ the same stop is $300 per contract. For a small account practicing NQ's volatility, MNQ turns an unaffordable trade into a survivable one." },
  ],
  "mcl-profile": [
    { type: "text", heading: "Micro Crude", body: "MCL is one-tenth of CL - tick value $1.00. Crude's headline-driven whipsaws are brutal on full-size; on MCL the same volatility costs a tenth as much. It's the right instrument to learn CL's false-breakout character without funding your tuition in $100 bills per mistake." },
    { type: "reveal", prompt: "CL gaps against you 50 ticks on an EIA print. On MCL, what's the per-contract damage?", answer: "$50. 50 ticks x $1.00 = $50 per MCL contract. On full CL that's $500. Crude's violent prints are why the Micro exists - you can't learn CL's character if one headline can take out a week's risk." },
  ],
  "ym-rty": [
    { type: "text", heading: "Two more equity indexes", body: "YM (the Dow) is the slow, blue-chip index - fewer, older companies, lower volatility, more orderly. RTY (the Russell 2000 small-caps) is the most volatile equity index - small caps swing hardest. Same strategies, different personalities: YM for patience, RTY for speed, ES in the middle." },
    { type: "text", heading: "Which index for which setup", body: "Breakout traders often like RTY because it moves furthest when it breaks. Trend followers may prefer ES or YM for their orderliness. Mean reversion can work on all three but RTY's extremes are more violent. Knowing which instrument fits your strategy is half of execution - the setup is the same, the terrain is different." },
    { type: "reveal", prompt: "You want to trade breakouts and capture the biggest moves. Which index futures is best suited?", answer: "RTY (Russell 2000). It's the most volatile equity index, so its breakouts travel furthest. The trade-off is wider stops and choppier behavior. ES is steadier but smaller moves; YM is slowest. Match the instrument to the strategy's appetite for volatility." },
  ],

  // ---------------- PLATFORM LITERACY ----------------
  "first-chart": [
    { type: "text", heading: "Symbol search is the front door", body: "Typing the symbol pulls the contract you want. Futures tickers carry month and year codes - ES1! is the continuous front-month ES, while an ES contract with a specific expiry is a real, tradable month. Knowing how your platform names contracts matters because it's easy to accidentally chart the wrong month and trade a thin, illiquid contract instead of the one everyone's actually in." },
    { type: "text", heading: "Tick vs. time-based charts", body: "Most beginners use time-based charts (1-min, 5-min) where a new bar forms every fixed interval. Tick charts print a new bar every N trades - so busy periods produce more bars and quiet periods fewer. Tick charts reveal the rhythm of participation; time charts reveal the clock. Try both on the same session and you'll start to feel when the market is 'on' versus just open." },
    { type: "reveal", prompt: "You open a 1-min chart and a daily chart of the same symbol. Which shows the bigger trend you're trading within?", answer: "The daily. Timeframe picks the question - the daily shows weeks of context, the 1-min shows the last few minutes of intraday action. Trading a 1-min setup against the daily trend is fighting the tide, which is why top-down analysis comes first." },
  ],
  "chart-types": [
    { type: "text", heading: "Bodies and wicks tell a story", body: "A long green body means buyers dominated the bar; a long lower wick means sellers pushed price down but buyers rejected it by the close. Reading candle bodies versus wicks is how you see who won the bar, not just where it ended. The close's location inside the bar's range is a fast read of control." },
    { type: "reveal", prompt: "A bar closes near its high with a tiny lower wick. What does that say about the bar's balance?", answer: "Buyers were in control - price spent the bar rising and closed at the top. A bar closing at its low with a tiny upper wick says the opposite. The close's location in the bar is a quick read of who won that bar." },
    { type: "text", heading: "Heikin-Ashi's hidden cost", body: "Heikin-Ashi averages the previous bar into the next, which smooths trends beautifully - but the displayed open, close, high, and low are not real market prices. Trailing a stop off a Heikin-Ashi low can sit well below where the market actually traded. Use it to see trend, then switch back to real candles for execution." },
  ],
  "timeframes-mtf": [
    { type: "text", heading: "Confluence is the goal", body: "When the 15-min trend, the 5-min pullback, and the 1-min entry all point the same way, that's confluence - multiple timeframes agreeing. Confluence doesn't guarantee a win, but it stacks probability in your favor. A 1-min entry alone is a coin flip; the same entry with 15-min confluence is a setup." },
    { type: "reveal", prompt: "You're long on a 1-min signal but the 15-min chart is in a clear downtrend. What's the honest read?", answer: "You're trading against the higher timeframe. The 1-min signal is real but it's a counter-trend bounce, which fails more often than it works. Either wait for the 15-min to turn, or take the trade tiny knowing it's a fade against the tide." },
    { type: "text", heading: "The timeframe-to-holding-period map", body: "A 1-min entry with a 5-point stop might be held 10 minutes; a daily breakout with a 50-point stop might be held a week. Stop distance and timeframe scale together, and so does your dollar risk per trade. Bigger timeframe means a bigger stop, which means smaller size for the same dollar risk." },
  ],
  "drawing-tools": [
    { type: "text", heading: "Horizontal levels beat diagonal lines", body: "Trendlines look clever but break often and depend on which points you connect. Horizontal support and resistance at round numbers and prior swing highs and lows are where real orders sit. Spend most of your drawing on horizontals - they're the levels institutions actually defend." },
    { type: "reveal", prompt: "You draw a Fibonacci retracement from a swing low to a swing high. What is it telling you?", answer: "Where pullbacks within that swing are likely to find support - the 38%, 50%, and 62% levels are watched by many traders, which is partly why they work. It's a map of probable pullback levels, not a guarantee. Use it to anticipate, then confirm with price action." },
    { type: "text", heading: "The measuring tool is a risk calculator", body: "Before you enter, draw the measuring tool from your entry to your stop. It shows the point distance; multiply by tick value and contracts and you have your dollar risk. Building the habit of measuring before clicking is how you stop guessing your risk and start knowing it." },
  ],
  "indicators": [
    { type: "text", heading: "Lag is the feature, not the bug", body: "Every indicator is computed from past prices, so it reacts after the fact. A moving average can't tell you where price is going; it tells you where price has been. That's still useful - it frames the trend - but expecting an indicator to lead is the beginner's trap. Price leads; indicators describe." },
    { type: "reveal", prompt: "RSI reads 72 (above 70, 'overbought') on an instrument in a strong uptrend. What's the disciplined read?", answer: "Overbought can persist for a long time in a trend. RSI alone is not a sell signal; it's a flag that price is extended. In a strong uptrend, overbought readings are normal. Use RSI with trend context, not against it." },
    { type: "text", heading: "Volume is the one indicator worth watching", body: "Volume tells you how much participation is behind a move. A breakout on rising volume has backing; a breakout on falling volume is suspect. Of all the indicators, volume is the least derived - it's a direct read of participation, and it confirms or questions every price move." },
  ],
  "watchlists-alerts": [
    { type: "text", heading: "Fewer instruments, deeper knowledge", body: "Watching three instruments every day for a month teaches you their personalities - how NQ behaves at the open, how CL reacts to the EIA report, how gold moves on a dollar spike. Scanning fifty instruments teaches you nothing about any of them. Depth beats breadth for a discretionary trader." },
    { type: "reveal", prompt: "You set an alert at your breakout level. It fires while you're away from the screen. What's the right response?", answer: "Check the chart - did price actually close beyond the level with volume, or did it just spike through and reverse? The alert tells you to look; it doesn't tell you to trade. An alert is a prompt, not an order." },
    { type: "text", heading: "Notification hygiene", body: "An alert that fires and leads to no action trains you to ignore alerts, which defeats the purpose. Review your alerts weekly and delete the ones you've stopped acting on. The alerts that remain should each map to a specific planned response." },
  ],
  "paper-replay": [
    { type: "text", heading: "Replay teaches reading, not feeling", body: "Bar replay is phenomenal for pattern recognition - you can practice 50 breakouts in an hour that would take weeks in real time. But replay has no stakes, so it teaches you to read charts without teaching you to manage yourself. Use it to sharpen your eyes, then accept that the emotional part is a separate skill." },
    { type: "reveal", prompt: "You're profitable in paper trading for a month. Does that mean you'll be profitable with real money?", answer: "Not necessarily. Paper removes the fear of loss, which is exactly what causes real-money mistakes. Paper proves your strategy can work; it doesn't prove you can execute it under pressure. Transition with small real size, not your full paper size." },
    { type: "text", heading: "The transition bridge", body: "When you move from paper to real, start with one Micro contract - real money, tiny stakes. The point isn't to make money; it's to feel the difference a real loss makes and to practice keeping your plan intact when you feel it. That bridge is where execution discipline is actually built." },
  ],
};